name: Practice-workflow
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: download code
              uses: actions/checkout@v3
            - name: Install bodejs
              uses: actions/setup-node@v3
            - name: install dependency
              run: npm ci
            - name: run lint
              run: npm run lint
              
    tests:
        runs-on: ubuntu-latest
        steps: 
        - name: download code
          uses: actions/checkout@v3
        - name: Install nodejs
          uses: actions/setup-node@v3
        - name: install dependency
          run: npm ci
        - name: run tests
          run: npm run test

    build:
        needs: tests
        runs-on: ubuntu-latest
        steps: 
        - name: download code
          uses: actions/checkout@v3
        - name: Install nodejs
          uses: actions/setup-node@v3
        - name: install dependency
          run: npm ci
        - name: build the app
          run: npm run build