name: Practice-workflow
on: push
jobs:
    tests:
        runs-on: ubuntu-latest
        steps: 
        - name: download code
          uses: actions/checkout@v3
        - name: Install nodejs
          uses: actions/setup-node@v3
        - name: install dependency
          run: npm ci
        - name: run tests
          run: npm test

    build:
        needs: tests
        runs-on: ubuntu-latest
        steps: 
        - name: download code
          uses: actions/checkout@v3
        - name: Install nodejs
          uses: actions/setup-node@v3
        - name: install dependency
          run: npm ci
        - name: build the app
          run: npm run build